import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QPoint
from PyQt5.QtGui import QCursor, QMouseEvent
from PyQt5.QtWidgets import QWidget, QApplication, QMainWindow
from db import DB


class Ui_MainWindow(QMainWindow):
    _startPos = None
    _endPos = None
    _isTracking = False
    def __init__(self):
        self.db = DB()
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setFixedSize(QSize(791, 640))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.msg = QtWidgets.QTableWidget(self.centralwidget)
        self.msg.setGeometry(QtCore.QRect(140, 90, 631, 491))
        self.msg.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msg.setAutoFillBackground(False)
        self.msg.setObjectName("msg")
        self.msg.setColumnCount(5)
        self.msg.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.msg.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.msg.setHorizontalHeaderItem(4, item)
        self.msg.setColumnWidth(0, 80)
        self.msg.setColumnWidth(1, 80)
        self.msg.setColumnWidth(2, 180)
        self.msg.setColumnWidth(3, 240)
        self.msg.setColumnWidth(4, 0)

        self.nichengshuru = QtWidgets.QLineEdit(self.centralwidget)
        self.nichengshuru.setGeometry(QtCore.QRect(510, 80, 161, 31))
        self.nichengshuru.setObjectName("nichengshuru")
        self.nichengshuru.hide()

        self.yuanmima = QtWidgets.QLineEdit(self.centralwidget)
        self.yuanmima.setGeometry(QtCore.QRect(510, 190, 161, 31))
        self.yuanmima.setText("")
        self.yuanmima.setObjectName("yuanmima")
        self.yuanmima.setEchoMode(QtWidgets.QLineEdit.Password)
        self.yuanmima.hide()
        self.xinmima = QtWidgets.QLineEdit(self.centralwidget)
        self.xinmima.setGeometry(QtCore.QRect(510, 260, 161, 31))
        self.xinmima.setObjectName("xinmima")
        self.xinmima.setEchoMode(QtWidgets.QLineEdit.Password)
        self.xinmima.hide()

        self.zhuxiao = QtWidgets.QPushButton(self.centralwidget)
        self.zhuxiao.setGeometry(QtCore.QRect(530, 440, 101, 31))
        self.zhuxiao.setStyleSheet("background-color: rgb(247,76,49);\n"
                                   "color: rgb(255, 255, 255);")
        self.zhuxiao.setObjectName("zhuxiao")
        self.zhuxiao.hide()

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(430, 85, 81, 21))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.label_3.hide()
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 200, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_2.hide()

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 230, 72, 21))
        self.label_5.setStyleSheet("font: 9pt \"楷体\"; color: red;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_3")
        self.label_5.hide()
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 50, 72, 21))
        self.label_4.setStyleSheet("font: 9pt \"楷体\"; color: red;")
        self.label_4.setText("修改成功")
        self.label_4.setObjectName("label_4")
        self.label_4.hide()

        self.delete_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_2.setGeometry(QtCore.QRect(20, 240, 93, 28))
        self.delete_2.setObjectName("delete_2")
        self.mima = QtWidgets.QPushButton(self.centralwidget)
        self.mima.setGeometry(QtCore.QRect(700, 260, 61, 28))
        self.mima.setObjectName("mima")
        self.mima.hide()
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.yonghuxinxi = QtWidgets.QPushButton(self.centralwidget)
        self.yonghuxinxi.setGeometry(QtCore.QRect(20, 80, 93, 28))
        self.yonghuxinxi.setObjectName("yonghuxinxi")
        self.nicheng = QtWidgets.QPushButton(self.centralwidget)
        self.nicheng.setGeometry(QtCore.QRect(700, 80, 61, 28))
        self.nicheng.setObjectName("nicheng")
        self.nicheng.hide()
        self.shuaxin = QtWidgets.QPushButton(self.centralwidget)
        self.shuaxin.setGeometry(QtCore.QRect(20, 190, 93, 28))
        self.shuaxin.setObjectName("bianji")
        self.user = QtWidgets.QTableWidget(self.centralwidget)
        self.user.setGeometry(QtCore.QRect(140, 30, 261, 581))
        self.user.setObjectName("user")
        self.user.setColumnCount(2)
        self.user.setRowCount(0)
        self.user.setColumnWidth(0, 80)
        self.user.setColumnWidth(1, 150)
        self.user.hide()
        item = QtWidgets.QTableWidgetItem()
        self.user.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.user.setHorizontalHeaderItem(1, item)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(320, 5, 371, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dateTimeEdit1 = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit1.setObjectName("dateTimeEdit1")
        self.horizontalLayout.addWidget(self.dateTimeEdit1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout.addWidget(self.dateTimeEdit)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 26))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.sousuo = QtWidgets.QPushButton(self.centralwidget)
        self.sousuo.setGeometry(QtCore.QRect(710, 35, 31, 31))
        self.sousuo.setStyleSheet("image: url(./搜索.png);")
        self.sousuo.setText("")
        self.sousuo.setObjectName("sousuo")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 5, 91, 24))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 40, 481, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)




    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle("信息管理")
        item = self.msg.horizontalHeaderItem(0)
        item.setText("用户名")
        item = self.msg.horizontalHeaderItem(1)
        item.setText("昵称")
        item = self.msg.horizontalHeaderItem(2)
        item.setText("发送时间")
        item = self.msg.horizontalHeaderItem(3)
        item.setText("发送内容")
        item = self.msg.horizontalHeaderItem(4)
        item.setText("id")
        self.delete_2.setText("删除")
        self.mima.setText("删除")
        self.pushButton.setText("消息记录")
        self.yonghuxinxi.setText("用户信息")
        self.nicheng.setText("编辑")
        self.shuaxin.setText("显示全部")
        item = self.user.horizontalHeaderItem(0)
        item.setText("用户名")
        item = self.user.horizontalHeaderItem(1)
        item.setText("昵称")
        self.label.setText("--")
        self.lineEdit.setPlaceholderText("查找消息记录")
        self.nichengshuru.setPlaceholderText(_translate("MainWindow", "输入新的昵称"))
        self.label_3.setText(_translate("MainWindow", "修改昵称："))
        self.label_2.setText(_translate("MainWindow", "修改密码："))
        self.yuanmima.setPlaceholderText(_translate("MainWindow", "输入原密码"))
        self.xinmima.setPlaceholderText(_translate("MainWindow", "输入新的密码"))
        self.nicheng.setText(_translate("MainWindow", "确定"))
        self.mima.setText(_translate("MainWindow", "确定"))
        self.zhuxiao.setText(_translate("MainWindow", "注销账号"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Ui_MainWindow()
    sys.exit(app.exec_())
